services:
  postgres:
    container_name: postgres-E
    image: postgres
    environment:
      POSTGRES_USER: knops
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-E:/data/postgres-E
    ports:
      - "4300:5432"
    networks:
      - postgres-E
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin-E
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-E:/var/lib/pgadmin-E
    ports:
      - "5051:80"
    networks:
      - postgres-E
    restart: unless-stopped
networks:
  postgres-E:
    driver: bridge

volumes:
  postgres-E:
  pgadmin-E: