services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: knops
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-E:/data/postgres
    ports:
      - "4300:5432"
    networks:
      - postgres-E
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-E:/var/lib/pgadmin-E
    ports:
      - "5051:80"
    networks:
      - postgres-E
    restart: unless-stopped
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
  apigw:
      build: 
        context: ./apigw
      container_name: apigw
      ports:
        - "8085:8085"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      networks:
        - spring
      depends_on:
        - eureka-server
        - videos

  videos:
      build:
        context: ./videos
      container_name: videos
      ports:
        - "8082:8082"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      networks:
        - spring
        - postgres-E
      depends_on:
        - eureka-server
        - postgres
        - authentification

  authentification:
      build:
        context: ./authentification
      container_name: authentification
      ports:
        - "8081:8081"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      networks:
        - spring
        - postgres-E
      depends_on:
        - eureka-server
        - postgres
  
  react:
    build:
      context: ./frontend
    container_name: react
    ports:
      - "4000:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres-E
    depends_on:
      - eureka-server
      - postgres
      - authentification
      - apigw
      - videos
networks:
  postgres-E:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres-E:
  pgadmin-E:
