services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: knops
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-E:/data/postgres-E
    ports:
      - "4300:5432"
    networks:
      - postgres-E
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-E:/var/lib/pgadmin-E
    ports:
      - "5051:80"
    networks:
      - postgres-E
    restart: unless-stopped
  eureka-server:
    image: armelnnomoko/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
  apigw:
      image: armelnnomoko/apigw:latest
      container_name: apigw
      ports:
        - "8085:8085"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      networks:
        - spring
      depends_on:
        - eureka-server
        - videos

  videos:
      image: armelnnomoko/videos:latest
      container_name: videos
      ports:
        - "8082:8082"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      networks:
        - spring
        - postgres-E
      depends_on:
        - eureka-server
        - postgres
        - authentification

  authentification:
      image: armelnnomoko/authentification:latest
      container_name: authentification
      ports:
        - "8081:8081"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      networks:
        - spring
        - postgres-E
      depends_on:
        - eureka-server
        - postgres

networks:
  postgres-E:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres-E:
  pgadmin-E: